# Generated by Django 5.1.6 on 2025-02-20 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "easyship_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("origin_line_1", models.CharField(max_length=255)),
                (
                    "origin_line_2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("origin_state", models.CharField(max_length=255)),
                ("origin_city", models.CharField(max_length=255)),
                ("origin_postal_code", models.CharField(max_length=255)),
                ("origin_country_alpha2", models.CharField(max_length=2)),
                ("origin_company_name", models.CharField(max_length=255)),
                ("origin_contact_name", models.CharField(max_length=255)),
                ("origin_contact_phone", models.CharField(max_length=255)),
                ("origin_contact_email", models.EmailField(max_length=254)),
                ("destination_line_1", models.CharField(max_length=255)),
                (
                    "destination_line_2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("destination_state", models.CharField(max_length=255)),
                ("destination_city", models.CharField(max_length=255)),
                ("destination_postal_code", models.CharField(max_length=255)),
                ("destination_country_alpha2", models.CharField(max_length=2)),
                ("destination_company_name", models.CharField(max_length=255)),
                ("destination_contact_name", models.CharField(max_length=255)),
                ("destination_contact_phone", models.CharField(max_length=255)),
                ("destination_contact_email", models.EmailField(max_length=254)),
                ("regulatory_identifiers", models.JSONField(blank=True, null=True)),
                (
                    "buyer_regulatory_identifiers",
                    models.JSONField(blank=True, null=True),
                ),
                ("incoterms", models.CharField(blank=True, max_length=255, null=True)),
                ("is_insured", models.BooleanField(default=False)),
                (
                    "platform_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "buyer_selected_courier_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("order_created_at", models.DateTimeField(blank=True, null=True)),
                ("allow_fallback", models.BooleanField(default=False)),
                ("apply_shipping_rules", models.BooleanField(default=True)),
                ("shipping_settings", models.JSONField()),
                ("parcels", models.JSONField()),
                ("status", models.CharField(default="PENDING", max_length=255)),
                (
                    "tracking_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("courier_tracking_numbers", models.JSONField(blank=True, null=True)),
                ("label_url", models.URLField(blank=True, null=True)),
                (
                    "courier_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "selected_courier_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "selected_courier_service",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("documents", models.JSONField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TrackingInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tracking_number",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("current_status", models.CharField(max_length=255)),
                (
                    "origin_country",
                    models.CharField(blank=True, max_length=2, null=True),
                ),
                (
                    "destination_country",
                    models.CharField(blank=True, max_length=2, null=True),
                ),
                ("estimated_delivery", models.DateTimeField(blank=True, null=True)),
                ("delivery_date", models.DateTimeField(blank=True, null=True)),
                ("carrier", models.CharField(default="EasyShip", max_length=255)),
                ("tracking_link", models.URLField(blank=True, null=True)),
                ("raw_response", models.JSONField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TrackingEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tracking_number", models.CharField(db_index=True, max_length=255)),
                ("status", models.CharField(max_length=255)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("timestamp", models.DateTimeField()),
                ("message", models.TextField(blank=True, null=True)),
                (
                    "tracking_status",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tracking_events",
                        to="main.booking",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
